package football_management;


import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ZAINI M
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        Name_Player = new javax.swing.JLabel();
        icon_list = new javax.swing.JButton();
        Subject = new javax.swing.JLabel();
        fifa = new javax.swing.JLabel();
        icon_player1 = new javax.swing.JButton();
        List_Group1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setBackground(new java.awt.Color(149, 165, 166));
        logout.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("LOGOUT");
        logout.setBorder(null);
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 120, 40));

        Name_Player.setBackground(new java.awt.Color(52, 73, 94));
        Name_Player.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 24)); // NOI18N
        Name_Player.setForeground(new java.awt.Color(255, 255, 255));
        Name_Player.setText("SUPERSTAR PLAYER");
        jPanel1.add(Name_Player, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, -1, -1));

        icon_list.setBackground(new java.awt.Color(46, 204, 113));
        icon_list.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 14)); // NOI18N
        icon_list.setForeground(new java.awt.Color(142, 68, 173));
        icon_list.setIcon(new javax.swing.ImageIcon("C:\\Users\\ZAINI M\\Pictures\\New Folder\\choice_96px.png")); // NOI18N
        icon_list.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        icon_list.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_listMouseClicked(evt);
            }
        });
        icon_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icon_listActionPerformed(evt);
            }
        });
        jPanel1.add(icon_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 170, 160));

        Subject.setBackground(new java.awt.Color(52, 73, 94));
        Subject.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 36)); // NOI18N
        Subject.setForeground(new java.awt.Color(255, 255, 255));
        Subject.setText("MENU FOOTBALL MANAGEMENT SYSTEM");
        jPanel1.add(Subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        fifa.setBackground(new java.awt.Color(52, 73, 94));
        fifa.setFont(new java.awt.Font("Lucida Handwriting", 3, 24)); // NOI18N
        fifa.setForeground(new java.awt.Color(255, 255, 255));
        fifa.setText("Fifa World Cup Qatar 2022");
        jPanel1.add(fifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 390, -1));

        icon_player1.setBackground(new java.awt.Color(46, 204, 113));
        icon_player1.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 14)); // NOI18N
        icon_player1.setForeground(new java.awt.Color(142, 68, 173));
        icon_player1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ZAINI M\\Pictures\\New Folder\\staff_96px.png")); // NOI18N
        icon_player1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        icon_player1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon_player1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icon_player1ActionPerformed(evt);
            }
        });
        jPanel1.add(icon_player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 170, 160));

        List_Group1.setBackground(new java.awt.Color(52, 73, 94));
        List_Group1.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 24)); // NOI18N
        List_Group1.setForeground(new java.awt.Color(255, 255, 255));
        List_Group1.setText("COUNTRY LIST");
        jPanel1.add(List_Group1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\ZAINI M\\Pictures\\New Folder\\sports-2467178_1280.jpg")); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 980, 660));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void icon_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_listMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_icon_listMouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure if you want to exit??", "WARNING!", dialogBtn);
        
        if (dialogResult == 0){
            System.exit(0);}
        else {
        }
        
    }//GEN-LAST:event_logoutActionPerformed

    private void icon_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icon_listActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Table n = new Table();
        n.setVisible(true);
    }//GEN-LAST:event_icon_listActionPerformed

    private void icon_player1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icon_player1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_icon_player1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel List_Group1;
    private javax.swing.JLabel Name_Player;
    private javax.swing.JLabel Subject;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel fifa;
    private javax.swing.JButton icon_list;
    private javax.swing.JButton icon_player1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
