/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package football_management;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ZAINI M
 */
public class Player extends javax.swing.JFrame {

    /**
     * Creates new form Player
     */
    private void Kosongkan_Form() {
        txt_nationality.setEditable(true);
        txt_nationality.setText(null);
        txt_nameplayer.setText(null);
        txt_club.setText(null);
        txt_ageplayer.setText(null);
        txt_number.setText(null);
    }
    public Player() {
        initComponents();
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_search = new javax.swing.JTextField();
        cancel_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        edit_btn = new javax.swing.JButton();
        save_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        subject2 = new javax.swing.JLabel();
        worldcup = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabListPlayer = new javax.swing.JTable();
        Name_Player = new javax.swing.JLabel();
        txt_nameplayer = new javax.swing.JTextField();
        Country_name = new javax.swing.JLabel();
        txt_number = new javax.swing.JTextField();
        NumberShirt = new javax.swing.JLabel();
        txt_club = new javax.swing.JTextField();
        Age = new javax.swing.JLabel();
        txt_nationality = new javax.swing.JTextField();
        NameClub = new javax.swing.JLabel();
        txt_ageplayer = new javax.swing.JTextField();
        search_btn = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        getContentPane().add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 630, 320, 30));

        cancel_btn.setBackground(new java.awt.Color(149, 165, 166));
        cancel_btn.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 14)); // NOI18N
        cancel_btn.setForeground(new java.awt.Color(255, 255, 255));
        cancel_btn.setText("CANCEL");
        cancel_btn.setBorder(null);
        cancel_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancel_btnMouseClicked(evt);
            }
        });
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });
        getContentPane().add(cancel_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 310, 100, 40));

        delete_btn.setBackground(new java.awt.Color(149, 165, 166));
        delete_btn.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 14)); // NOI18N
        delete_btn.setForeground(new java.awt.Color(255, 255, 255));
        delete_btn.setText("DELETE");
        delete_btn.setBorder(null);
        delete_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_btnMouseClicked(evt);
            }
        });
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        getContentPane().add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 100, 40));

        edit_btn.setBackground(new java.awt.Color(149, 165, 166));
        edit_btn.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 14)); // NOI18N
        edit_btn.setForeground(new java.awt.Color(255, 255, 255));
        edit_btn.setText("EDIT");
        edit_btn.setBorder(null);
        edit_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });
        getContentPane().add(edit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 100, 40));

        save_btn.setBackground(new java.awt.Color(149, 165, 166));
        save_btn.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 14)); // NOI18N
        save_btn.setForeground(new java.awt.Color(255, 255, 255));
        save_btn.setText("SAVE");
        save_btn.setBorder(null);
        save_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        getContentPane().add(save_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 100, 40));

        back_btn.setBackground(new java.awt.Color(149, 165, 166));
        back_btn.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 14)); // NOI18N
        back_btn.setForeground(new java.awt.Color(255, 255, 255));
        back_btn.setText("BACK");
        back_btn.setBorder(null);
        back_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_btnMouseClicked(evt);
            }
        });
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        getContentPane().add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 630, 90, 40));

        subject2.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 36)); // NOI18N
        subject2.setText("LIST SUPERSTAR PLAYER ");
        getContentPane().add(subject2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, -1));

        worldcup.setBackground(new java.awt.Color(52, 73, 94));
        worldcup.setFont(new java.awt.Font("Lucida Handwriting", 3, 18)); // NOI18N
        worldcup.setText("Fifa World Cup Qatar 2022");
        getContentPane().add(worldcup, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        TabListPlayer.setAutoCreateRowSorter(true);
        TabListPlayer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TabListPlayer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        TabListPlayer.setDragEnabled(true);
        TabListPlayer.setGridColor(new java.awt.Color(0, 0, 0));
        TabListPlayer.setShowGrid(true);
        TabListPlayer.setSurrendersFocusOnKeystroke(true);
        TabListPlayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabListPlayerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabListPlayer);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 990, 210));

        Name_Player.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        Name_Player.setForeground(new java.awt.Color(255, 255, 255));
        Name_Player.setText("NAME PLAYER");
        getContentPane().add(Name_Player, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        txt_nameplayer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_nameplayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameplayerActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nameplayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 240, -1));

        Country_name.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        Country_name.setForeground(new java.awt.Color(255, 255, 255));
        Country_name.setText("NATIONALITY");
        getContentPane().add(Country_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        txt_number.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_numberActionPerformed(evt);
            }
        });
        getContentPane().add(txt_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 70, -1));

        NumberShirt.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        NumberShirt.setForeground(new java.awt.Color(255, 255, 255));
        NumberShirt.setText("NUMBER SHIRT");
        getContentPane().add(NumberShirt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        txt_club.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_club.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_clubActionPerformed(evt);
            }
        });
        getContentPane().add(txt_club, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 240, -1));

        Age.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        Age.setForeground(new java.awt.Color(255, 255, 255));
        Age.setText("AGE");
        getContentPane().add(Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        txt_nationality.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_nationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nationalityActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 180, -1));

        NameClub.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        NameClub.setForeground(new java.awt.Color(255, 255, 255));
        NameClub.setText("CLUB NAME");
        getContentPane().add(NameClub, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        txt_ageplayer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_ageplayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ageplayerActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ageplayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 70, -1));

        search_btn.setBackground(new java.awt.Color(149, 165, 166));
        search_btn.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 14)); // NOI18N
        search_btn.setForeground(new java.awt.Color(255, 255, 255));
        search_btn.setText("SEARCH");
        search_btn.setBorder(null);
        search_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_btnMouseClicked(evt);
            }
        });
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });
        getContentPane().add(search_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 90, 30));

        bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\ZAINI M\\Downloads\\soccer-7594706_1280.jpg")); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private DefaultTableModel tableModel;
    private ResultSet resultSet;
    public final void showTable(){
        try {
            Connection conn = ConnectionDatabase.configDB();
            
            Object[] columnTitle = {"NO","NATIONALITY","NAME PLAYER","CLUB NAME","AGE","NUMBER SHIRT"};
            tableModel = new DefaultTableModel(null,columnTitle);
            TabListPlayer.setModel(tableModel);
            Statement statement = conn.createStatement();
            tableModel.getDataVector().removeAllElements();
            
            resultSet = statement.executeQuery("SELECT * FROM list_player");
            while(resultSet.next()){
                Object[] data = {
                    resultSet.getString("NO"),
                    resultSet.getString("NATIONALITY"),
                    resultSet.getString("NAME_PLAYER"),
                    resultSet.getString("CLUB"),
                    resultSet.getString("AGE"),
                    resultSet.getString("NUMBER SHIRT")
                        
                };
                tableModel.addRow(data);
            }
            System.out.println("");
            
        } catch (SQLException e) {
            System.out.println("");
            System.out.println(e);
        }
    }
    private void TabListPlayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabListPlayerMouseClicked
        // TODO add your handling code here:
        int baris = TabListPlayer.rowAtPoint(evt.getPoint());

        String nationality = TabListPlayer.getValueAt(baris, 1).toString();
        txt_nationality.setText(nationality);

        String nameplayer = TabListPlayer.getValueAt(baris, 2).toString();
        txt_nameplayer.setText(nameplayer);

        String club = TabListPlayer.getValueAt(baris, 3).toString();
        txt_club.setText(club);

        String age = TabListPlayer.getValueAt(baris, 4).toString();
        txt_ageplayer.setText(age);

        String number = TabListPlayer.getValueAt(baris, 5).toString();
        txt_number.setText(number);

    }//GEN-LAST:event_TabListPlayerMouseClicked

    private void txt_nameplayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameplayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameplayerActionPerformed

    private void txt_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_numberActionPerformed

    private void txt_clubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_clubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_clubActionPerformed

    private void txt_nationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nationalityActionPerformed

    private void txt_ageplayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ageplayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ageplayerActionPerformed

    private void back_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_back_btnMouseClicked

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Menu n = new Menu();
        n.setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    private final String regex = "\\s";
    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        // TODO add your handling code here:
        try {
            String negara = txt_nationality.getText();
            String namapemain = txt_nameplayer.getText();
            String klub = txt_club.getText();
            String umur = txt_ageplayer.getText();
            String nomor = txt_number.getText();
            System.out.println(namapemain.matches(regex));
            if ((negara.isEmpty()||negara.length()<3)||(namapemain.isEmpty()||namapemain.matches(regex))||(klub.isEmpty()||namapemain.matches(regex))||(klub.isEmpty()||klub.matches(regex))||(umur.isEmpty()||umur.matches(regex))||(nomor.isEmpty()||nomor.matches(regex))){
                JOptionPane.showMessageDialog(null, "DATA INVALID","Failed",JOptionPane.ERROR_MESSAGE);
            
        }else {
            String sql = "INSERT INTO `list_player`(`NATIONALITY`, `NAME_PLAYER`, `CLUB`, `AGE`, `NUMBER SHIRT`) VALUES ('" + txt_nationality.getText() + "','" + txt_nameplayer.getText() + "','" + txt_club.getText() +"','" + txt_ageplayer.getText() + "','" + txt_number.getText() + "')";
            Connection conn = ConnectionDatabase.configDB();
            PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            showTable();
            JOptionPane.showMessageDialog(null, "DATA SAVED SUCCESFULLY");
            Kosongkan_Form();
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showConfirmDialog(this, e.getMessage());       
        }
    }//GEN-LAST:event_save_btnActionPerformed

    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed
        // TODO add your handling code here:
         try {
            String negara = txt_nationality.getText();
            String namapemain = txt_nameplayer.getText();
            String klub = txt_club.getText();
            String umur = txt_ageplayer.getText();
            String nomor = txt_number.getText();
            System.out.println(namapemain.matches(regex));
            if ((negara.isEmpty()||negara.length()<3)||(namapemain.isEmpty()||namapemain.matches(regex))||(klub.isEmpty()||namapemain.matches(regex))||(klub.isEmpty()||klub.matches(regex))||(umur.isEmpty()||umur.matches(regex))||(nomor.isEmpty()||nomor.matches(regex))){
                JOptionPane.showMessageDialog(null, "DATA INVALID","Failed",JOptionPane.ERROR_MESSAGE);
        }else {
            String sql = "UPDATE `list_player` SET `NATIONALITY`='"+txt_nationality.getText()+"',`NAME_PLAYER`='"+txt_nameplayer.getText()+"',`CLUB`='"+txt_club.getText()+"',`AGE`='"+txt_ageplayer.getText()+"',`NUMBER SHIRT`='"+txt_number.getText()+"' WHERE NATIONALITY='"+txt_nationality.getText()+"'";
            Connection con = ConnectionDatabase.configDB();
            PreparedStatement pstm = con.prepareStatement(sql);
            pstm.execute();
            showTable();
            JOptionPane.showMessageDialog(null, "DATA EDITED SUCCESSFULLY"); 
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
        showTable();
        Kosongkan_Form();

    }//GEN-LAST:event_edit_btnActionPerformed

    private void delete_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_btnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_btnMouseClicked

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
         try {
            String negara = txt_nationality.getText();
            String namapemain = txt_nameplayer.getText();
            String klub = txt_club.getText();
            String umur = txt_ageplayer.getText();
            String nomor = txt_number.getText();
            System.out.println(namapemain.matches(regex));
            if ((negara.isEmpty()||negara.length()<3)||(namapemain.isEmpty()||namapemain.matches(regex))||(klub.isEmpty()||namapemain.matches(regex))||(klub.isEmpty()||klub.matches(regex))||(umur.isEmpty()||umur.matches(regex))||(nomor.isEmpty()||nomor.matches(regex))){
                JOptionPane.showMessageDialog(null, "DATA INVALID","Failed",JOptionPane.ERROR_MESSAGE);
        }else {
            String sql = "DELETE FROM `list_player` WHERE NATIONALITY='"+ txt_nationality.getText() + "'";
            Connection conn = ConnectionDatabase.configDB();
            PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            showTable();
            JOptionPane.showMessageDialog(null, "DATA DELETED SUCCESFULLY");
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
        showTable();
        Kosongkan_Form();

    }//GEN-LAST:event_delete_btnActionPerformed

    private void cancel_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_btnMouseClicked
        // TODO add your handling code here:
        Kosongkan_Form();
    }//GEN-LAST:event_cancel_btnMouseClicked

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void search_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_btnMouseClicked
        // TODO add your handling code here:
        try {
            Connection conn = ConnectionDatabase.configDB();
            
            Object[] columnTitle = {"NO","NATIONALITY","NAME PLAYER","CLUB NAME","AGE","NUMBER SHIRT"};
            tableModel = new DefaultTableModel(null,columnTitle);
            TabListPlayer.setModel(tableModel);
            Statement statement = conn.createStatement();
            tableModel.getDataVector().removeAllElements();
            
            resultSet = statement.executeQuery("SELECT * FROM list_player WHERE NATIONALITY LIKE '%" + txt_search.getText() + "%'");
            while(resultSet.next()){
                Object[] data = {
                    resultSet.getString("NO"),
                    resultSet.getString("NATIONALITY"),
                    resultSet.getString("NAME_PLAYER"),
                    resultSet.getString("CLUB"),
                    resultSet.getString("AGE"),
                    resultSet.getString("NUMBER SHIRT")
                        
                };
                tableModel.addRow(data);
            }
            System.out.println("");
            
        } catch (SQLException e) {
            System.out.println("");
            System.out.println(e);
        }
    
    

    }//GEN-LAST:event_search_btnMouseClicked

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_btnActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Player().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age;
    private javax.swing.JLabel Country_name;
    private javax.swing.JLabel NameClub;
    private javax.swing.JLabel Name_Player;
    private javax.swing.JLabel NumberShirt;
    private javax.swing.JTable TabListPlayer;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel bg;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton edit_btn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton save_btn;
    private javax.swing.JButton search_btn;
    private javax.swing.JLabel subject2;
    private javax.swing.JTextField txt_ageplayer;
    private javax.swing.JTextField txt_club;
    private javax.swing.JTextField txt_nameplayer;
    private javax.swing.JTextField txt_nationality;
    private javax.swing.JTextField txt_number;
    private javax.swing.JTextField txt_search;
    private javax.swing.JLabel worldcup;
    // End of variables declaration//GEN-END:variables
}
