/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package football_management;

import system_football_management.Login;

/**
 *
 * @author ZAINI M
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bg = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_login = new javax.swing.JButton();
        Subject1 = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        subject = new javax.swing.JLabel();
        icon_user = new javax.swing.JLabel();
        Fullname = new javax.swing.JLabel();
        icon_name = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        subject1 = new javax.swing.JLabel();
        icon_email = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        txt_username3 = new javax.swing.JTextField();
        icon_User1 = new javax.swing.JLabel();
        Fullname1 = new javax.swing.JLabel();
        txt_name1 = new javax.swing.JTextField();
        btn_login1 = new javax.swing.JButton();
        subject2 = new javax.swing.JLabel();
        subject3 = new javax.swing.JLabel();
        cb_agree = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\ZAINI M\\Downloads\\football-1396740_1280.jpg")); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-460, 0, 880, 610));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 610));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_login.setBackground(new java.awt.Color(204, 204, 204));
        btn_login.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 12)); // NOI18N
        btn_login.setText("LOGIN");
        btn_login.setBorder(null);
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_loginMouseClicked(evt);
            }
        });
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        jPanel2.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 580, 70, 20));

        Subject1.setBackground(new java.awt.Color(52, 73, 94));
        Subject1.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 36)); // NOI18N
        Subject1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ZAINI M\\Pictures\\New Folder\\icons8_registration_48.png")); // NOI18N
        Subject1.setText("REGISTER");
        jPanel2.add(Subject1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 240, -1));

        Password.setBackground(new java.awt.Color(52, 73, 94));
        Password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Password.setText("PASSWORD");
        jPanel2.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 110, -1));

        subject.setBackground(new java.awt.Color(52, 73, 94));
        subject.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        subject.setText("Have an account ?");
        jPanel2.add(subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, 120, -1));

        icon_user.setIcon(new javax.swing.ImageIcon("C:\\Users\\ZAINI M\\Pictures\\New Folder\\icons8_key_16.png")); // NOI18N
        jPanel2.add(icon_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 20, 30));

        Fullname.setBackground(new java.awt.Color(52, 73, 94));
        Fullname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Fullname.setText("USERNAME");
        jPanel2.add(Fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 180, -1));

        icon_name.setIcon(new javax.swing.ImageIcon("C:\\Users\\ZAINI M\\Pictures\\New Folder\\icons8_name_16.png")); // NOI18N
        jPanel2.add(icon_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 20, 30));

        txt_username.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 290, -1));

        txt_password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 290, 20));

        subject1.setBackground(new java.awt.Color(52, 73, 94));
        subject1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        subject1.setForeground(new java.awt.Color(204, 204, 204));
        subject1.setText("By Sign up, You agree to our");
        jPanel2.add(subject1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 180, -1));

        icon_email.setIcon(new javax.swing.ImageIcon("C:\\Users\\ZAINI M\\Pictures\\New Folder\\icons8_Open_email_16.png")); // NOI18N
        jPanel2.add(icon_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 20, 30));

        Email.setBackground(new java.awt.Color(52, 73, 94));
        Email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Email.setText("MOBILE PHONE OR EMAIL ");
        jPanel2.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 180, -1));

        txt_username3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_username3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txt_username3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_username3ActionPerformed(evt);
            }
        });
        jPanel2.add(txt_username3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 290, -1));

        icon_User1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ZAINI M\\Pictures\\New Folder\\icons8_user_16.png")); // NOI18N
        jPanel2.add(icon_User1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 20, 30));

        Fullname1.setBackground(new java.awt.Color(52, 73, 94));
        Fullname1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Fullname1.setText("FULL NAME");
        jPanel2.add(Fullname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 180, -1));

        txt_name1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_name1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txt_name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_name1ActionPerformed(evt);
            }
        });
        jPanel2.add(txt_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 290, -1));

        btn_login1.setBackground(new java.awt.Color(126, 214, 223));
        btn_login1.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 14)); // NOI18N
        btn_login1.setText("SIGN UP");
        btn_login1.setBorder(null);
        btn_login1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 90, 30));

        subject2.setBackground(new java.awt.Color(52, 73, 94));
        subject2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        subject2.setText("Sign in to see Menu System");
        jPanel2.add(subject2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 170, -1));

        subject3.setBackground(new java.awt.Color(52, 73, 94));
        subject3.setText("Terms, Data Policy and Cookies Policy");
        jPanel2.add(subject3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 240, -1));

        cb_agree.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cb_agree.setText("I agree with term and Conditions");
        cb_agree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_agreeActionPerformed(evt);
            }
        });
        jPanel2.add(cb_agree, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 210, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 0, 440, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login1ActionPerformed
        // TODO add your handling code here:
//        if(cb_agree.isSelected()){
//            
//        }
    }//GEN-LAST:event_btn_login1ActionPerformed

    private void txt_username3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_username3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_username3ActionPerformed

    private void txt_name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_name1ActionPerformed

    private void cb_agreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_agreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_agreeActionPerformed

    private void btn_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Login n = new Login();
        n.setVisible(true);
    }//GEN-LAST:event_btn_loginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Fullname;
    private javax.swing.JLabel Fullname1;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Subject1;
    private javax.swing.JLabel bg;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_login1;
    private javax.swing.JCheckBox cb_agree;
    private javax.swing.JLabel icon_User1;
    private javax.swing.JLabel icon_email;
    private javax.swing.JLabel icon_name;
    private javax.swing.JLabel icon_user;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel subject;
    private javax.swing.JLabel subject1;
    private javax.swing.JLabel subject2;
    private javax.swing.JLabel subject3;
    private javax.swing.JTextField txt_name1;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    private javax.swing.JTextField txt_username3;
    // End of variables declaration//GEN-END:variables
}
